version: 2.0

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.14.0-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm test
