version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

executors:
  node-browsers-docker:
    parameters:
      node-version:
        # renovate datasource=node-version depName=node
        default: 20.12.2
        type: string
    docker:
      - image: cimg/node:<<parameters.node-version>>-browsers
    resource_class: small

workflows:
  version: 2
  build-and-test:
    jobs:
      - pix_ui_install
      - pix_ui_lint:
          requires:
            - pix_ui_install
          filters:
            branches:
              ignore:
                - gh-pages

      - pix_ui_test:
          requires:
            - pix_ui_install
          filters:
            branches:
              ignore:
                - gh-pages
      - try-scenarios:
          requires:
            - pix_ui_install
          matrix:
            parameters:
              try-scenario:
                - embroider-safe
                - embroider-optimized
          filters:
            branches:
              ignore:
                - gh-pages
      - chromatic-deployment:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  pix_ui_install:
    executor:
      name: node-docker
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: ~/pix-ui
          paths:
            - .

  pix_ui_lint:
    executor:
      name: node-docker
    working_directory: ~/pix-ui
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run lint:scss

  pix_ui_test:
    executor: node-browsers-docker
    working_directory: ~/pix-ui
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - browser-tools/install-chrome
      - run: npm test

  try-scenarios:
    executor: node-browsers-docker
    working_directory: ~/pix-ui
    parameters:
      try-scenario:
        type: string
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - browser-tools/install-chrome
      - run: npx ember try:one << parameters.try-scenario >>

  chromatic-deployment:
    executor: node-browsers-docker
    working_directory: ~/pix-ui
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - run: npm run chromatic -- --auto-accept-changes
