version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.19.0-browsers
    resource_class: medium+
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run lint:scss
      - run: npm test
      - run: npx ember try:one embroider-safe
