version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint-and-test:
          matrix:
            parameters:
              node-version:
                - "16.20.1"
                - "18.17.0"
                - "20.8.0"
          filters:
            branches:
              ignore:
                - gh-pages
      - try-scenarios:
          matrix:
            parameters:
              try-scenario:
                - embroider-safe
                - embroider-optimized
              node-version:
                - "16.20.1"
                - "18.17.0"
                - "20.8.0"
          filters:
            branches:
              ignore:
                - gh-pages
      - chromatic-deployment:
          matrix:
            parameters:
              node-version:
                - "18.17.0"
                - "20.8.0"
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  lint-and-test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    resource_class: medium+
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run lint:scss
      - run: npm test

  try-scenarios:
    parameters:
      try-scenario:
        type: string
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    resource_class: large
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm ci
      - run: npx ember try:one << parameters.try-scenario >>

  chromatic-deployment:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run chromatic -- --auto-accept-changes
