version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.12.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm test
