version: 2.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.11.0-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm test
