version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
      - lint-and-test:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - install
      - try-scenarios:
          matrix:
            parameters:
              try-scenario:
                - embroider-safe
                - embroider-optimized
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - install
      - chromatic-deployment:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - install

jobs:
  install:
    docker:
      - image: cimg/node:19.9.0-browsers
    resource_class: medium+
    working_directory: ~/pix-ui
    steps:
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: ~/pix-ui
          paths:
            - .

  lint-and-test:
    docker:
      - image: cimg/node:19.9.0-browsers
    resource_class: medium+
    working_directory: ~/pix-ui
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run lint:scss
      - run: npm test

  try-scenarios:
    parameters:
      try-scenario:
        type: string
    docker:
      - image: cimg/node:19.9.0-browsers
    resource_class: medium+
    working_directory: ~/pix-ui
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npx ember try:one << parameters.try-scenario >>

  chromatic-deployment:
    docker:
      - image: cimg/node:19.9.0-browsers
    working_directory: ~/pix-ui
    steps:
      - attach_workspace:
          at: ~/pix-ui
      - run: npm run chromatic -- --auto-accept-changes
