version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

executors:
  node-browsers-docker:
    parameters:
      node-version:
        # renovate datasource=node-version depName=node
        default: 20.17.0
        type: string
    docker:
      - image: cimg/node:<<parameters.node-version>>-browsers
    resource_class: small

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint-and-test:
          filters:
            branches:
              ignore:
                - gh-pages
      - chromatic-deployment:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  lint-and-test:
    executor: node-browsers-docker
    resource_class: medium
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run lint:scss
      - run: npm test

  chromatic-deployment:
    executor: node-browsers-docker
    resource_class: medium
    steps:
      - checkout
      - run: npm ci
      - run: npm run chromatic -- --auto-accept-changes
