export const ICONS = {
  add: { default: 'add' },
  arrowBottom: { default: 'arrowDown' },
  arrowLeft: { default: 'arrowLeft' },
  arrowRight: { default: 'arrowRight' },
  arrowTop: { default: 'arrowUp' },
  assignment: { default: 'assignment', plainIcon: 'assignment_plain' },
  awards: { default: 'awards', plainIcon: 'awards_plain' },
  bell: { default: 'bell', plainIcon: 'bell_plain' },
  book: { default: 'book', plainIcon: 'book_plain' },
  bookAlt: { default: 'bookAlt', plainIcon: 'bookAlt_plain' },
  bookmark: { default: 'bookmark', plainIcon: 'bookmark_plain' },
  buildings: { default: 'building' },
  calendar: { default: 'calendar', plainIcon: 'calendar_plain' },
  campaign: { default: 'campaign', plainIcon: 'campaign_plain' },
  cancel: { default: 'closeCircle', plainIcon: 'closeCircle_plain' },
  chat: { default: 'chat', plainIcon: 'chat_plain' },
  check: { default: 'check' },
  checkCircle: { default: 'checkCircle', plainIcon: 'checkCircle_plain' },
  chevronBottom: { default: 'chevronDown' },
  chevronLeft: { default: 'chevronLeft' },
  chevronRight: { default: 'chevronRight' },
  chevronTop: { default: 'chevronUp' },
  time: { default: 'time', plainIcon: 'time_plain' },
  close: { default: 'close' },
  codeNumber: { default: 'codeNumber', plainIcon: 'codeNumber_plain' },
  conversionPath: { default: 'conversationPath' },
  copy: { default: 'copy', plainIcon: 'copy_plain' },
  delete: { default: 'delete', plainIcon: 'delete_plain' },
  desktopOff: { default: 'desktopOff', plainIcon: 'desktopOff_plain' },
  doneAll: { default: 'doneAll' },
  doorOpen: { default: 'doorOpen', plainIcon: 'doorOpen_plain' },
  download: { default: 'download' },
  edit: { default: 'edit', plainIcon: 'edit_plain' },
  error: { default: 'errorCircle', plainIcon: 'errorCircle_plain' },
  extension: { default: 'extension', plainIcon: 'extension_plain' },
  eye: { default: 'eye', plainIcon: 'eye_plain' },
  eyeOff: { default: 'eyeOff', plainIcon: 'eyeOff_plain' },
  favorite: { default: 'heart', plainIcon: 'heart_plain' },
  flag: { default: 'flag', plainIcon: 'flag_plain' },
  globe: { default: 'globe' },
  help: { default: 'helpCircle', plainIcon: 'helpCircle_plain' },
  home: { default: 'home', plainIcon: 'home_plain' },
  image: { default: 'image', plainIcon: 'image_plain' },
  inboxIn: { default: 'inboxIn', plainI: 'inboxIn_plain' },
  info: { default: 'infoCircle', plainIcon: 'infoCircle_plain' },
  infoUser: { default: 'infoUser', plainIcon: 'infoUser_plain' },
  inventory: { default: 'archive', plainIcon: 'archive_plain' },
  language: { default: 'language' },
  link: { default: 'link' },
  lock: { default: 'lock', plainIcon: 'lock_plain' },
  login: { default: 'login' },
  logout: { default: 'logout' },
  mapPin: { default: 'mapPin', plainIcon: 'mapPin_plain' },
  minus: { default: 'checkIndeterminate' },
  mobile: { default: 'smartphone', plainIcon: 'smartphone_plain' },
  mobileOff: { default: 'smartphoneOff', plainIcon: 'smartphoneOff_plain' },
  moreHoriz: { default: 'moreHoriz' },
  moreVert: { default: 'moreVert' },
  newRealease: { default: 'newReleases', plainIcon: 'newReleases_plain' },
  openNew: { default: 'openNew' },
  pauseCircle: { default: 'pauseCircle', plainIcon: 'pauseCircle_plain' },
  percent: { default: 'percent' },
  personAdd: { default: 'personAdd', plainIcon: 'personAdd_plain' },
  playCircle: { default: 'playCircle', plainIcon: 'playCircle_plain' },
  power: { default: 'power' },
  profileShare: { default: 'profileShare', plainIcon: 'profileShare_plain' },
  readMore: { default: 'readMore' },
  refresh: { default: 'refresh' },
  search: { default: 'search' },
  seat: { default: 'seat' },
  session: { default: 'eventDate', plainIcon: 'eventDate_plain' },
  settings: { default: 'settings', plainIcon: 'settings_plain' },
  share: { default: 'share', plainIcon: 'share_plain' },
  shieldPerson: { default: 'shieldPerson', plainIcon: 'shieldPerson_plain' },
  signpost: { default: 'signpost', plainIcon: 'signpost_plain' },
  sort: { default: 'sort' },
  sortAz: { default: 'sortAz' },
  speed: { default: 'speed', plainIcon: 'speed_plain' },
  star: { default: 'star', plainIcon: 'star_plain' },
  stopCircle: { default: 'stopCircle', plainIcon: 'stopCircle_plain' },
  tablet: { default: 'tablet', plainIcon: 'tablet_plain' },
  tabletOff: { default: 'tabletOff', plainIcon: 'tabletOff_plain' },
  thumbUp: { default: 'like', plainIcon: 'like_plain' },
  tools: { default: 'tools' },
  trendingDown: { default: 'trendingDown' },
  trendingFlat: { default: 'trendingFlat' },
  trendingUp: { default: 'trendingUp' },
  upload: { default: 'upload' },
  userCircle: { default: 'userCircle', plainIcon: 'userCircle_plain' },
  users: { default: 'users', plainIcon: 'users_plain' },
  videoCam: { default: 'videocam', plainIcon: 'videocam_plain' },
  volumeOff: { default: 'volumeOff', plainIcon: 'volumeOff_plain' },
  volumeOn: { default: 'volumeOn', plainIcon: 'volumeOn_plain' },
  warning: { default: 'warning', plainIcon: 'warning_plain' },
};
