export const ICONS = {
  add: { default: 'add' },
  arrowBottom: { default: 'arrow_downward' },
  arrowLeft: { default: 'arrow_back' },
  arrowRight: { default: 'arrow_forward' },
  arrowTop: { default: 'arrow_upward' },
  assignment: { default: 'assignment', plainIcon: 'assignment_plainIcon' },
  awards: { default: 'social_leaderboard', plainIcon: 'social_leaderboard_plainIcon' },
  bell: { default: 'notifications', plainIcon: 'notifications_plainIcon' },
  book: { default: 'menu_book', plainIcon: 'menu_book_plainIcon' },
  bookmark: { default: 'bookmark', plainIcon: 'bookmark_plainIcon' },
  buildings: { default: 'location_city' },
  calendar: { default: 'today', plainIcon: 'today_plainIcon' },
  campaign: { default: 'campaign', plainIcon: 'campaign_plainIcon' },
  cancel: { default: 'cancel', plainIcon: 'cancel_plainIcon' },
  check: { default: 'check' },
  checkCircle: { default: 'check_circle', plainIcon: 'check_circle_plainIcon' },
  chevronBottom: { default: 'arrow_drop_down' },
  chevronLeft: { default: 'chevron_left' },
  chevronRight: { default: 'chevron_right' },
  chevronTop: { default: 'arrow_drop_up' },
  clock: { default: 'schedule', plainIcon: 'schedule_plainIcon' },
  close: { default: 'close' },
  cloudUpload: { default: 'cloud_upload', plainIcon: 'cloud_upload_plainIcon' },
  conversionPath: { default: 'conversion_path' },
  copy: { default: 'content_copy', plainIcon: 'content_copy_plainIcon' },
  delete: { default: 'delete', plainIcon: 'delete_plainIcon' },
  down: { default: 'keyboard_arrow_down' },
  download: { default: 'download' },
  edit: { default: 'edit_square', plainIcon: 'edit_square_plainIcon' },
  error: { default: 'error', plainIcon: 'error_plainIcon' },
  extension: { default: 'extension', plainIcon: 'extension_plainIcon' },
  eye: { default: 'visibility', plainIcon: 'visibility_plainIcon' },
  eyeOff: { default: 'visibility_off', plainIcon: 'visibility_off_plainIcon' },
  favorite: { default: 'favorite', plainIcon: 'favorite_plainIcon' },
  flag: { default: 'flag', plainIcon: 'flag_plainIcon' },
  globe: { default: 'globe' },
  help: { default: 'help', plainIcon: 'help_plainIcon' },
  home: { default: 'home', plainIcon: 'home_plainIcon' },
  image: { default: 'image', plainIcon: 'image_plainIcon' },
  info: { default: 'info', plainIcon: 'info_plainIcon' },
  infoUser: { default: 'contact_page', plainIcon: 'contact_page_plainIcon' },
  inventory: { default: 'inventory_2', plainIcon: 'inventory_2_plainIcon' },
  language: { default: 'language' },
  link: { default: 'link' },
  lock: { default: 'lock', plainIcon: 'lock_plainIcon' },
  logout: { default: 'logout' },
  mapPin: { default: 'location_on', plainIcon: 'location_on_plainIcon' },
  minus: { default: 'check_indeterminate_small' },
  moreHoriz: { default: 'more_horiz' },
  moreVert: { default: 'more_vert' },
  newRealease: { default: 'new_releases', plainIcon: 'new_releases_plainIcon' },
  openNew: { default: 'open_in_new' },
  pauseCircle: { default: 'pause_circle', plainIcon: 'pause_circle_plainIcon' },
  playCircle: { default: 'play_circle', plainIcon: 'play_circle_plainIcon' },
  power: { default: 'power_settings_new' },
  readMore: { default: 'read_more' },
  refresh: { default: 'refresh' },
  search: { default: 'search' },
  seat: { default: 'airline_seat_recline_normal' },
  session: { default: 'event_note', plainIcon: 'event_note_plainIcon' },
  settings: { default: 'settings', plainIcon: 'settings_plainIcon' },
  share: { default: 'share', plainIcon: 'share_plainIcon' },
  shieldPerson: { default: 'shield_person', plainIcon: 'shield_person_plainIcon' },
  signpost: { default: 'signpost', plainIcon: 'signpost_plainIcon' },
  smartphone: { default: 'smartphone', plainIcon: 'smartphone_plainIcon' },
  sort: { default: 'swap_vert' },
  sortAz: { default: 'sort_by_alpha' },
  star: { default: 'star', plainIcon: 'star_plainIcon' },
  stopCircle: { default: 'stop_circle', plainIcon: 'stop_circle_plainIcon' },
  tablet: { default: 'tablet_android', plainIcon: 'tablet_android_plainIcon' },
  thumbUp: { default: 'thumb_up', plainIcon: 'thumb_up_plainIcon' },
  tools: { default: 'construction' },
  up: { default: 'keyboard_arrow_up' },
  upload: { default: 'upload' },
  uploadFile: { default: 'upload_file', plainIcon: 'upload_file_plainIcon' },
  userCircle: { default: 'account_circle', plainIcon: 'account_circle_plainIcon' },
  users: { default: 'group', plainIcon: 'group_plainIcon' },
  videoCam: { default: 'videocam', plainIcon: 'videocam_plainIcon' },
  volumeOff: { default: 'volume_off', plainIcon: 'volume_off_plainIcon' },
  volumeOn: { default: 'volume_up', plainIcon: 'volume_up_plainIcon' },
  warning: { default: 'warning', plainIcon: 'warning_plainIcon' },
};
