module.exports = () => ({
  'free-solid-svg-icons': [
    'arrow-left',
    'arrow-right',
    'bullhorn',
    'check',
    'chevron-up',
    'chevron-down',
    'circle-check',
    'circle-exclamation',
    'circle-info',
    'circle-question',
    'circle-xmark',
    'earth-europe',
    'eye',
    'eye-slash',
    'magnifying-glass',
    'plus',
    'triangle-exclamation',
    'up-right-from-square',
    'user',
    'xmark',
  ],
});
