name: Deploy Pix UI Storybook

on: 
  workflow_dispatch: 
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Deploy storybook to Github Pages
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: 1024pix:${{ secrets.GITHUB_TOKEN }}