name: release

permissions:
  id-token: write # necessary for publishing to npm
  contents: write # necessary for pushing to gh-pages branch

on:
  push:
    branches:
      - dev
  repository_dispatch:
    types: [ 'deploy' ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - uses: 1024pix/pix-actions/release@main
        id: semantic
        with:
          npmPublish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}

      - name: Deploy storybook to Github Pages
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: 1024pix:${{ secrets.GITHUB_TOKEN }}
